kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: thin-disk
spec:
  :
    -
  resources:
    requests:
      storage: 2Gi