apiVersion: apps/v1
kind: Deployment
metadata:
  name: nascop-redis-performance-deployment
  labels:
    app: nascop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-performance-pod
      app: nascop
  template:
    metadata:
      name: redis-performance-pod
      labels:
        name: redis-performance-pod
        app: nascop

    spec:
      containers:
      - name: redis
        image: redis
        args: ["--appendonly yes"]
        volumeMounts:
          - mountPath: /data
            name: redis-performance-data
        ports:
        - containerPort: 6379
      volumes:
        - name: redis-performance-data
          persistentVolumeClaim:
            claimName: redis-performance-data
          
