apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 10.230.51.85
  ports:
  - port: 1
- addresses:
  - ip: 10.230.51.82
  ports:
  - port: 1
- addresses:
  - ip: 10.230.51.79
  ports:
  - port: 1
